version: '3.9'

services:
    db:
        container_name: zach_blog_db_dev
        image: mysql:8.0
        restart: always
        command: mysqld --default-authentication-plugin=mysql_native_password
        volumes:
          - ./data:/var/lib/mysql
        env_file:
          - ./.env.dev
        environment:
          - MYSQL_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
          - MYSQL_USER=${SQL_USER}
          - MYSQL_PASSWORD=${SQL_PASSWORD}
          - MYSQL_DATABASE=${SQL_DATABASE}
          - MYSQL_HOST=${SQL_HOST}
        ports:
          - 3306:3306

    nginx:
        container_name: zach_blog_ngnix_dev
        restart: always
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        ports:
            - 80:80
        volumes:
            - static_volume:/code/backend/django_static
            - ./docker/nginx/development:/etc/nginx/conf.d
        depends_on:
            - backend

    backend:
        container_name: zach_blog_backend_dev
        restart: always
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile

        entrypoint: /code/docker/backend/wsgi-entrypoint.sh
        volumes:
            - .:/code
            - static_volume:/code/backend/django_static
        env_file:
            - ./.env.dev
        expose:
            - 8000
        ports:
            - "8000:8000"
        depends_on:
          - db
        links:
          - db

volumes:
    static_volume: { }
    pgdata: { }

