version: "3.9"

services:
  db:
    container_name: zach_blog_db
    image: mysql:8.0
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data:/var/lib/mysql
    env_file:
      - ./.env.dev
    environment:
      - MYSQL_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
      - MYSQL_USER=${SQL_USER}
      - MYSQL_PASSWORD=${SQL_PASSWORD}
      - MYSQL_DATABASE=${SQL_DATABASE}
    ports:
      - 3306:3306

  web:
    container_name: zach_blog_backend
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - static_volume:/code/backend/django_static
    env_file:
      - ./.env.dev
    entrypoint:
      - /usr/local/bin/docker-entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
volumes:
    static_volume: { }

